/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/cameras": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Cameras */
        get: operations["get_cameras_api_v1_cameras_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/experiments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Experiments */
        get: operations["get_experiments_api_v1_experiments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/experiments/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Experiment Filter Options */
        get: operations["get_experiment_filter_options_api_v1_experiments_options_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/experiments/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Experiment */
        get: operations["get_experiment_api_v1_experiments__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/experiments/{run_id}/dose-series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run Dose Series */
        get: operations["get_run_dose_series_api_v1_experiments__run_id__dose_series_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/experiments/{run_id}/dose-series/ensure": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ensure Run Dose Series */
        post: operations["ensure_run_dose_series_api_v1_experiments__run_id__dose_series_ensure_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/experiments/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Exposure Events */
        get: operations["get_exposure_events_api_v1_experiments__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/experiments/{run_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Experiment */
        get: operations["export_experiment_api_v1_experiments__run_id__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/experiments/{run_id}/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Experiment Metrics */
        get: operations["get_experiment_metrics_api_v1_experiments__run_id__metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/experiments/{run_id}/observer-dose-series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Observer Dose Series */
        get: operations["get_observer_dose_series_api_v1_experiments__run_id__observer_dose_series_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/experiments/{run_id}/resources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Experiment Resources */
        get: operations["get_experiment_resources_api_v1_experiments__run_id__resources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/experiments/{run_id}/resources/{resource_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Experiment Resource */
        get: operations["download_experiment_resource_api_v1_experiments__run_id__resources__resource_name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/experiments/{run_id}/snapshots/{snapshot_id}/analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Snapshot Analysis */
        get: operations["get_snapshot_analysis_api_v1_experiments__run_id__snapshots__snapshot_id__analysis_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/experiments/{run_id}/snapshots/{snapshot_id}/series/{series}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Snapshot Series */
        get: operations["get_snapshot_series_api_v1_experiments__run_id__snapshots__snapshot_id__series__series__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Live */
        get: operations["get_live_api_v1_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/live/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Live Events */
        get: operations["get_live_events_api_v1_live_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/logs/archives": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Log Archives */
        get: operations["get_log_archives_api_v1_logs_archives_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/logs/context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Log Context */
        get: operations["get_log_context_api_v1_logs_context_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/logs/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Log Entries */
        get: operations["get_log_entries_api_v1_logs_entries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/logs/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Log Events */
        get: operations["get_log_events_api_v1_logs_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subsystems": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Subsystems */
        get: operations["get_subsystems_api_v1_subsystems_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Live */
        get: operations["health_live_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Ready */
        get: operations["health_ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BatchExposureSummary */
        BatchExposureSummary: {
            /** Actual Dose */
            actual_dose: number | null;
            /** Actual Time */
            actual_time: number | null;
            /** Created At */
            created_at: number | null;
            /** End Reason */
            end_reason: string | null;
            /** Name */
            name: string;
            /** Queue Position */
            queue_position?: number | null;
            /** Run Id */
            run_id: string | null;
            /** Sample Number */
            sample_number?: number | null;
            /** State */
            state: string;
            /** Status */
            status: string | null;
            /** Target Dose */
            target_dose: number | null;
            /** Target Time */
            target_time: number | null;
        };
        /** BatchPlanEntrySummary */
        BatchPlanEntrySummary: {
            /** Attempt Count */
            attempt_count: number;
            /** Cumulative Actual */
            cumulative_actual: number | null;
            /** Mode */
            mode: string;
            /** Order */
            order: number;
            /** Overshoot */
            overshoot: number;
            /** Remainder */
            remainder: number;
            /** Sample Number */
            sample_number: number;
            /** State */
            state: string;
            /** Target */
            target: number;
        };
        /** BatchSlotSummary */
        BatchSlotSummary: {
            /** Abort Reasons */
            abort_reasons: string[];
            /** Attempt Count */
            attempt_count: number;
            /** Cumulative Actual Dose */
            cumulative_actual_dose: number;
            /** Cumulative Actual Time */
            cumulative_actual_time: number;
            /** First Target Dose */
            first_target_dose: number | null;
            /** First Target Time */
            first_target_time: number | null;
            /** Sample Number */
            sample_number: number;
            /** State */
            state: string;
        };
        /** BatchSummary */
        BatchSummary: {
            /**
             * Authoritative
             * @default false
             */
            authoritative: boolean;
            /** Batch Id */
            batch_id?: string | null;
            /** Cancel Pending */
            cancel_pending?: boolean | null;
            /** Controller Message */
            controller_message?: string | null;
            /** Controller Phase */
            controller_phase?: string | null;
            /** Decision Kind */
            decision_kind?: string | null;
            /** Decision Message */
            decision_message?: string | null;
            /** Execution Mode */
            execution_mode?: string | null;
            /** Exposures */
            exposures: components["schemas"]["BatchExposureSummary"][];
            /** Lease Owned */
            lease_owned?: boolean | null;
            /** Manifest Status */
            manifest_status?: string | null;
            /** Name */
            name: string | null;
            /** Paused */
            paused?: boolean | null;
            /**
             * Plan Entries
             * @default []
             */
            plan_entries: components["schemas"]["BatchPlanEntrySummary"][];
            /** Possibly Truncated */
            possibly_truncated: boolean;
            /** Remaining Count */
            remaining_count: number;
            /** Revision */
            revision?: number | null;
            /** Selection Source */
            selection_source: string;
            /** Slots */
            slots: components["schemas"]["BatchSlotSummary"][];
            /** Unplaced Exposures */
            unplaced_exposures: components["schemas"]["BatchExposureSummary"][];
        };
        /** CameraSummary */
        CameraSummary: {
            /** Configured */
            configured: boolean;
            /** Id */
            id: string;
            /** Name */
            name: string;
        };
        /** CamerasResponse */
        CamerasResponse: {
            /**
             * Items
             * @default []
             */
            items: components["schemas"]["CameraSummary"][];
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: "1";
        };
        /** ExperimentDataIssueResponse */
        ExperimentDataIssueResponse: {
            /** Kind */
            kind: string;
            /** Message */
            message: string;
            /** Resource Name */
            resource_name: string | null;
            /** Section */
            section: string;
        };
        /** ExperimentDetailResponse */
        ExperimentDetailResponse: {
            /** End Metadata */
            end_metadata: {
                [key: string]: unknown;
            } | null;
            /** Issues */
            issues: components["schemas"]["ExperimentDataIssueResponse"][];
            log_range: components["schemas"]["LogRangeResponse"];
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            metrics: components["schemas"]["ExperimentMetricsResponse"];
            /** Resources */
            resources: components["schemas"]["RegisteredResourceResponse"][];
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: "1";
            /** Settings */
            settings: {
                [key: string]: unknown;
            };
            /** Snapshots */
            snapshots: components["schemas"]["SnapshotResponse"][];
            summary: components["schemas"]["ExperimentListItemResponse"];
            /** Tags */
            tags: {
                [key: string]: string | number;
            };
        };
        /** ExperimentDetails */
        ExperimentDetails: {
            /** Base Pressure */
            base_pressure: number | null;
            /** Description */
            description: string;
            /** Flow Sccm */
            flow_sccm: number | null;
            /** Name */
            name: string;
            /** Operating Pressure */
            operating_pressure: number | null;
            /** Operator */
            operator: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Sample Number */
            sample_number?: number | null;
            /** Sample Type */
            sample_type: string;
            /** Target Dose */
            target_dose: number | null;
            /** Target Time */
            target_time: number | null;
            /** Zr Filter */
            zr_filter: string;
        };
        /** ExperimentFilterOptionsResponse */
        ExperimentFilterOptionsResponse: {
            /** Actual Dose Max */
            actual_dose_max: number | null;
            /** Actual Dose Min */
            actual_dose_min: number | null;
            /** Created Max */
            created_max: number | null;
            /** Created Min */
            created_min: number | null;
            /** Operators */
            operators: string[];
            /** Runtime Max */
            runtime_max: number | null;
            /** Runtime Min */
            runtime_min: number | null;
            /** Samples */
            samples: string[];
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: "1";
            /** Target Dose Max */
            target_dose_max: number | null;
            /** Target Dose Min */
            target_dose_min: number | null;
            /** Zr Filters */
            zr_filters: string[];
        };
        /** ExperimentFiltersResponse */
        ExperimentFiltersResponse: {
            /** Created Max */
            created_max: number | null;
            /** Created Min */
            created_min: number | null;
            /** Max Actual Dose */
            max_actual_dose: number | null;
            /** Max Runtime */
            max_runtime: number | null;
            /** Max Target Dose */
            max_target_dose: number | null;
            /** Min Actual Dose */
            min_actual_dose: number | null;
            /** Min Runtime */
            min_runtime: number | null;
            /** Min Target Dose */
            min_target_dose: number | null;
            /** Name */
            name: string | null;
            /** Operator */
            operator: string | null;
            /** Sample */
            sample: string | null;
            /** Zr Filter */
            zr_filter: string | null;
        };
        /** ExperimentListItemResponse */
        ExperimentListItemResponse: {
            /** Actual Dose */
            actual_dose: number | null;
            /** Blank Thickness Nm */
            blank_thickness_nm: number | null;
            /** Created At */
            created_at: number;
            /** Description */
            description: string;
            /** Effective Dose Rate */
            effective_dose_rate: number | null;
            /** End Reason */
            end_reason: string | null;
            /** Exposed Thickness Nm */
            exposed_thickness_nm: number | null;
            /** Name */
            name: string;
            /** Operator */
            operator: string | null;
            /** Percent Development */
            percent_development: number | null;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Runtime */
            runtime: number | null;
            /** Sample */
            sample: string | null;
            /** Status */
            status: string | null;
            /** Target Dose */
            target_dose: number | null;
            /** Target Time */
            target_time: number | null;
            /** Zr Filter */
            zr_filter: string | null;
        };
        /** ExperimentMetricsResponse */
        ExperimentMetricsResponse: {
            /** Blank Average Nm */
            blank_average_nm: number | null;
            /** Degraded */
            degraded: boolean;
            /** Error */
            error: string | null;
            /** Exposed Average Nm */
            exposed_average_nm: number | null;
            /** Measurements */
            measurements: components["schemas"]["MetricMeasurementResponse"][];
            /** Percent Development */
            percent_development: number | null;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: "1";
        };
        /** ExperimentPageResponse */
        ExperimentPageResponse: {
            filters: components["schemas"]["ExperimentFiltersResponse"];
            /** Items */
            items: components["schemas"]["ExperimentListItemResponse"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: "1";
            /** Total Count */
            total_count: number;
            /** Total Pages */
            total_pages: number;
        };
        /** ExperimentReason */
        ExperimentReason: {
            /** Reason */
            reason: string;
            /** Status */
            status: string;
            /** Subsystem */
            subsystem: string;
        };
        /** ExperimentResourcesResponse */
        ExperimentResourcesResponse: {
            /** Items */
            items: components["schemas"]["RegisteredResourceResponse"][];
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: "1";
        };
        /** ExperimentSummary */
        ExperimentSummary: {
            details: components["schemas"]["ExperimentDetails"] | null;
            phase: components["schemas"]["PublicExperimentPhase"];
            /** Reasons */
            reasons: components["schemas"]["ExperimentReason"][];
        };
        /** ExposureEventResponse */
        ExposureEventResponse: {
            /** Capture Session Id */
            capture_session_id?: string | null;
            /**
             * Event Id
             * Format: uuid
             */
            event_id: string;
            /** Ingest Unix Ns */
            ingest_unix_ns: number;
            /** Kind */
            kind: string;
            /** Next Sequence */
            next_sequence?: number | null;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Producer Monotonic Ns */
            producer_monotonic_ns?: number | null;
            /** Producer Unix Ns */
            producer_unix_ns: number;
            /** Runtime Seconds */
            runtime_seconds?: number | null;
            /** Sequence */
            sequence: number;
            /**
             * Stream Id
             * Format: uuid
             */
            stream_id: string;
            /** Stream Name */
            stream_name: string;
        };
        /** ExposureEventTimelineResponse */
        ExposureEventTimelineResponse: {
            /** Complete */
            complete: boolean;
            /** Events */
            events: components["schemas"]["ExposureEventResponse"][];
            /** Issues */
            issues: string[];
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: "1";
            /** Wall Time Origin Unix Ns */
            wall_time_origin_unix_ns?: number | null;
        };
        /** GraphAnnotationResponse */
        GraphAnnotationResponse: {
            /**
             * Category
             * @enum {string}
             */
            category: "lifecycle" | "triggers" | "transmitting";
            /**
             * Event Id
             * Format: uuid
             */
            event_id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "point" | "interval";
            /** Label */
            label: string;
            /** Producer Unix Ns */
            producer_unix_ns: number;
            /**
             * Projection Quality
             * @enum {string}
             */
            projection_quality: "producer" | "runtime_hint" | "exact" | "next_pulse";
            /** Source */
            source: string;
            /** Value */
            value?: boolean | null;
            /** X */
            x: number;
            /** X End */
            x_end?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "starting" | "ready" | "degraded";
            system_state?: components["schemas"]["HealthState"] | null;
        };
        /**
         * HealthState
         * @enum {string}
         */
        HealthState: "ok" | "warning" | "error" | "unknown";
        /**
         * IssueSeverity
         * @enum {string}
         */
        IssueSeverity: "warning" | "error";
        /** LiveResponse */
        LiveResponse: {
            batch: components["schemas"]["BatchSummary"];
            experiment: components["schemas"]["ExperimentSummary"];
            /** Generated At */
            generated_at: number;
            progress: components["schemas"]["ProgressSummary"];
            queue: components["schemas"]["QueueSummary"];
            /** Revision */
            revision: number;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: "1";
            /** Sources */
            sources: {
                [key: string]: components["schemas"]["SourceSummary"];
            };
            stage: components["schemas"]["StageSummary"];
            /** Subsystems */
            subsystems: components["schemas"]["SubsystemSummary"][];
            system: components["schemas"]["SystemSummary"];
        };
        /** LogArchiveResponse */
        LogArchiveResponse: {
            /** End Line Exclusive */
            end_line_exclusive: number;
            /** End Timestamp */
            end_timestamp: number | null;
            /** Is Current */
            is_current: boolean;
            /** Name */
            name: string;
            /** Start Line */
            start_line: number;
            /** Start Timestamp */
            start_timestamp: number | null;
        };
        /** LogArchivesResponse */
        LogArchivesResponse: {
            /** Items */
            items: components["schemas"]["LogArchiveResponse"][];
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: "1";
        };
        /** LogContextResponse */
        LogContextResponse: {
            /** Archive */
            archive: string | null;
            /** Line From */
            line_from?: number | null;
            /** Line To */
            line_to?: number | null;
            /** Matching Archives */
            matching_archives: string[];
            /** Message */
            message: string | null;
            /**
             * Resolution
             * @enum {string}
             */
            resolution: "event" | "time" | "unscoped";
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: "1";
            /** Since */
            since: number | null;
            /** Until */
            until: number | null;
        };
        /** LogEntryResponse */
        LogEntryResponse: {
            /** L Type */
            l_type: string;
            /** Level */
            level: string;
            /** Line */
            line: number;
            /** Message */
            message: string;
            /** Origin Uuid */
            origin_uuid: string | null;
            /** Record */
            record: {
                [key: string]: unknown;
            };
            /** Subsystem */
            subsystem: string;
            /** Timestamp */
            timestamp: number | null;
        };
        /** LogEventResponse */
        LogEventResponse: {
            /** Data End */
            data_end: {
                [key: string]: unknown;
            };
            /** Data Start */
            data_start: {
                [key: string]: unknown;
            };
            /** E Type */
            e_type: string;
            /** End Line */
            end_line?: number | null;
            /** End Timestamp */
            end_timestamp: number | null;
            /** Event Id */
            event_id: string;
            /** Level */
            level: string;
            /** Message */
            message: string;
            /** Start Line */
            start_line: number;
            /** Start Timestamp */
            start_timestamp: number | null;
        };
        /** LogEventsResponse */
        LogEventsResponse: {
            /** Items */
            items: components["schemas"]["LogEventResponse"][];
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: "1";
        };
        /** LogFiltersResponse */
        LogFiltersResponse: {
            /** Exclude Types */
            exclude_types: string[] | null;
            /** L Type */
            l_type: string | null;
            /** Level */
            level: string | null;
            /** Line From */
            line_from: number | null;
            /** Line To */
            line_to: number | null;
            /** Min Level */
            min_level: string | null;
            /** Origin Uuid */
            origin_uuid: string | null;
            /** Since */
            since: number | null;
            /** Until */
            until: number | null;
        };
        /** LogPageResponse */
        LogPageResponse: {
            /** Archive */
            archive: string;
            /** At Tail */
            at_tail: boolean;
            filters: components["schemas"]["LogFiltersResponse"];
            /** First Line */
            first_line?: number | null;
            /** Has After */
            has_after: boolean;
            /** Has Before */
            has_before: boolean;
            /** Last Line */
            last_line?: number | null;
            /** Rows */
            rows: components["schemas"]["LogEntryResponse"][];
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: "1";
        };
        /** LogRangeResponse */
        LogRangeResponse: {
            /** Complete */
            complete: boolean;
            /** Created At */
            created_at: number | null;
            /** Ended At */
            ended_at: number | null;
            /** Event Id */
            event_id: string;
        };
        /** MetricMeasurementResponse */
        MetricMeasurementResponse: {
            /** Goodness Of Fit */
            goodness_of_fit: number;
            /**
             * Spot Type
             * @enum {string}
             */
            spot_type: "exposed" | "blank";
            /** Thickness Nm */
            thickness_nm: number;
        };
        /** ObserverDoseComparisonResponse */
        ObserverDoseComparisonResponse: {
            /** Errors */
            errors: string[];
            /**
             * Resolution
             * @enum {string}
             */
            resolution: "full" | "thumbnail";
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: "1";
            /** Series */
            series: components["schemas"]["ObserverDoseSeriesResponse"][];
            /**
             * Status
             * @enum {string}
             */
            status: "missing" | "complete";
            /**
             * Wall Origin Quality
             * @enum {string}
             */
            wall_origin_quality: "unavailable" | "observer_first_capture" | "run_preinit";
        };
        /** ObserverDoseCompletenessResponse */
        ObserverDoseCompletenessResponse: {
            /** Excluded Snapshot Count */
            excluded_snapshot_count: number;
            /** Included Snapshot Count */
            included_snapshot_count: number;
            /** Snapshot Count */
            snapshot_count: number;
            /** Unknown Eligibility Snapshot Count */
            unknown_eligibility_snapshot_count: number;
            /** Unknown Step Mode Snapshot Count */
            unknown_step_mode_snapshot_count: number;
        };
        /** ObserverDosePointResponse */
        ObserverDosePointResponse: {
            /** Cumulative Dose Mj Cm2 */
            cumulative_dose_mj_cm2: number;
            /** Dose Increment Mj Cm2 */
            dose_increment_mj_cm2: number;
            /** Represented Pulse Count */
            represented_pulse_count: number;
            /** Source Sequence */
            source_sequence?: number | null;
            /** Wall Elapsed Seconds */
            wall_elapsed_seconds: number;
        };
        /** ObserverDoseSeriesResponse */
        ObserverDoseSeriesResponse: {
            /**
             * Algorithm
             * @enum {string}
             */
            algorithm: "captured" | "legacy_compensated";
            /** Algorithm Version */
            algorithm_version: string;
            /** Average Pulse Dose Mj Cm2 */
            average_pulse_dose_mj_cm2: number;
            /** Calibration Hash */
            calibration_hash: string;
            /** Calibration Name */
            calibration_name: string;
            /**
             * Calibration Profile Id
             * Format: uuid
             */
            calibration_profile_id: string;
            /** Calibration Revision */
            calibration_revision: number;
            completeness: components["schemas"]["ObserverDoseCompletenessResponse"];
            /** Issues */
            issues: string[];
            /** Points */
            points: components["schemas"]["ObserverDosePointResponse"][];
            /** Pulse Count */
            pulse_count: number;
            /** Raw Point Count */
            raw_point_count: number;
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /** Source Id */
            source_id: string;
            /** Source Kind */
            source_kind: string;
            /**
             * Status
             * @enum {string}
             */
            status: "complete" | "incomplete";
            /** Total Dose Mj Cm2 */
            total_dose_mj_cm2: number;
            /** Transfer Count */
            transfer_count: number;
        };
        /**
         * ProgressMode
         * @enum {string}
         */
        ProgressMode: "none" | "dose" | "time" | "indeterminate";
        /** ProgressSummary */
        ProgressSummary: {
            /** Current */
            current: number | null;
            mode: components["schemas"]["ProgressMode"];
            /** Percent */
            percent?: number | null;
            /** Target */
            target: number | null;
            /** Unit */
            unit: string | null;
        };
        /**
         * PublicExperimentPhase
         * @enum {string}
         */
        PublicExperimentPhase: "checking_system" | "preparing" | "initializing" | "exposing" | "stopping" | "idle";
        /**
         * PublicStageState
         * @enum {string}
         */
        PublicStageState: "idle" | "homing" | "moving" | "offline" | "unknown";
        /** QueueSummary */
        QueueSummary: {
            /** Current Batch Remaining Count */
            current_batch_remaining_count: number;
            /** Remaining Count */
            remaining_count: number;
        };
        /** RegisteredResourceResponse */
        RegisteredResourceResponse: {
            /** Available */
            available: boolean;
            /** Downloadable */
            downloadable: boolean;
            /** Error */
            error: string | null;
            /** Name */
            name: string;
            /** Resource Type */
            resource_type: string;
            /** Size Bytes */
            size_bytes?: number | null;
        };
        /** RunDosePointResponse */
        RunDosePointResponse: {
            /** Cumulative Dose Mj Cm2 */
            cumulative_dose_mj_cm2: number;
            /** Dose Increment Mj Cm2 */
            dose_increment_mj_cm2: number;
            /** Dose Rate Mj Cm2 S */
            dose_rate_mj_cm2_s: number;
            /** Represented Pulse Count */
            represented_pulse_count: number;
            /** Runtime Seconds */
            runtime_seconds: number;
            /** Source Index */
            source_index: number;
            /** Source Sequence */
            source_sequence?: number | null;
            /** Wall Elapsed Seconds */
            wall_elapsed_seconds: number;
        };
        /** RunDoseSeriesResponse */
        RunDoseSeriesResponse: {
            /** Annotations */
            annotations: components["schemas"]["GraphAnnotationResponse"][];
            /** Errors */
            errors: string[];
            /** Issues */
            issues: string[];
            /** Points */
            points: components["schemas"]["RunDosePointResponse"][];
            /** Raw Pulse Count */
            raw_pulse_count: number;
            /**
             * Resolution
             * @enum {string}
             */
            resolution: "full" | "thumbnail";
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Runtime Basis */
            runtime_basis?: string | null;
            /**
             * Schema Version
             * @default 3
             * @constant
             */
            schema_version: "3";
            /**
             * Source
             * @constant
             */
            source: "persisted";
            /** Source Id */
            source_id?: string | null;
            /** Source Kind */
            source_kind?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "waiting_for_completion" | "missing" | "busy" | "complete" | "error";
            /**
             * Time Mode
             * @enum {string}
             */
            time_mode: "runtime" | "wall";
        };
        /** SnapshotAnalysisResponse */
        SnapshotAnalysisResponse: {
            /** Average Pulse Dose Mj Cm2 */
            average_pulse_dose_mj_cm2: number;
            /** Backfill Error */
            backfill_error: string | null;
            /** Delivered Dose Rate Mj Cm2 S */
            delivered_dose_rate_mj_cm2_s: number;
            /** Effective Duration Seconds */
            effective_duration_seconds: number;
            /** Is Step Exposure */
            is_step_exposure: boolean;
            /** Metadata Backfilled */
            metadata_backfilled: boolean;
            /** Pulse Span Seconds */
            pulse_span_seconds: number;
            /** Runtime Contribution Seconds */
            runtime_contribution_seconds: number;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: "1";
            /**
             * Step Mode Source
             * @enum {string}
             */
            step_mode_source: "provided" | "inferred" | "native";
            /** Total Dose Mj Cm2 */
            total_dose_mj_cm2: number;
            /** Wall Duration Seconds */
            wall_duration_seconds: number;
        };
        /** SnapshotGraphSeriesResponse */
        SnapshotGraphSeriesResponse: {
            /** Annotations */
            annotations: components["schemas"]["GraphAnnotationResponse"][];
            /** Issues */
            issues: string[];
            /** Point Count */
            point_count: number;
            /** Rolling Window */
            rolling_window: number;
            /**
             * Schema Version
             * @default 2
             * @constant
             */
            schema_version: "2";
            /**
             * Series
             * @enum {string}
             */
            series: "voltage" | "peaks" | "dose";
            /**
             * Snapshot Id
             * Format: uuid
             */
            snapshot_id: string;
            /** X */
            x: number[];
            /** X Label */
            x_label: string;
            /** Y */
            y: number[];
            /** Y Label */
            y_label: string;
        };
        /** SnapshotResponse */
        SnapshotResponse: {
            /** Final Sequence */
            final_sequence?: number | null;
            /**
             * Format
             * @enum {string}
             */
            format: "legacy_npz" | "euv_hdf5";
            metadata: components["schemas"]["RegisteredResourceResponse"] | null;
            /**
             * Snapshot Id
             * Format: uuid
             */
            snapshot_id: string;
            waveform: components["schemas"]["RegisteredResourceResponse"];
        };
        /**
         * SourceState
         * @enum {string}
         */
        SourceState: "available" | "not_applicable" | "degraded" | "stale" | "unavailable";
        /** SourceSummary */
        SourceSummary: {
            /** Attempted At */
            attempted_at: number | null;
            /** Error */
            error: string | null;
            /** Observed At */
            observed_at: number | null;
            state: components["schemas"]["SourceState"];
        };
        /** StagePosition */
        StagePosition: {
            /** Theta */
            theta: number;
            /** Z */
            z: number;
        };
        /** StageSummary */
        StageSummary: {
            /** Current Sample Number */
            current_sample_number?: number | null;
            position: components["schemas"]["StagePosition"] | null;
            state: components["schemas"]["PublicStageState"];
        };
        /** SubsystemIssue */
        SubsystemIssue: {
            /** Message */
            message: string;
            severity: components["schemas"]["IssueSeverity"];
        };
        /** SubsystemSummary */
        SubsystemSummary: {
            /** Connected */
            connected: boolean;
            /** Critical */
            critical: boolean;
            /** Issues */
            issues: components["schemas"]["SubsystemIssue"][];
            /** Name */
            name: string;
            /** Primary Status */
            primary_status: string;
        };
        /** SubsystemsResponse */
        SubsystemsResponse: {
            /** Generated At */
            generated_at: number;
            /** Items */
            items: components["schemas"]["SubsystemSummary"][];
            /** Revision */
            revision: number;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: "1";
            system: components["schemas"]["SystemSummary"];
        };
        /** SystemIssue */
        SystemIssue: {
            /** Message */
            message: string;
            severity: components["schemas"]["IssueSeverity"];
            /** Source */
            source: string;
        };
        /** SystemSummary */
        SystemSummary: {
            /** Issues */
            issues: components["schemas"]["SystemIssue"][];
            /** Label */
            label: string;
            state: components["schemas"]["HealthState"];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_cameras_api_v1_cameras_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CamerasResponse"];
                };
            };
        };
    };
    get_experiments_api_v1_experiments_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number | null;
                name?: string | null;
                created_min?: number | null;
                created_max?: number | null;
                min_actual_dose?: number | null;
                max_actual_dose?: number | null;
                min_target_dose?: number | null;
                max_target_dose?: number | null;
                min_runtime?: number | null;
                max_runtime?: number | null;
                zr_filter?: string | null;
                sample?: string | null;
                operator?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentPageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_experiment_filter_options_api_v1_experiments_options_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentFilterOptionsResponse"];
                };
            };
        };
    };
    get_experiment_api_v1_experiments__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_dose_series_api_v1_experiments__run_id__dose_series_get: {
        parameters: {
            query?: {
                time_mode?: string;
                resolution?: string;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDoseSeriesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ensure_run_dose_series_api_v1_experiments__run_id__dose_series_ensure_post: {
        parameters: {
            query?: {
                time_mode?: string;
                resolution?: string;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDoseSeriesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_exposure_events_api_v1_experiments__run_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExposureEventTimelineResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_experiment_api_v1_experiments__run_id__export_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_experiment_metrics_api_v1_experiments__run_id__metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentMetricsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_observer_dose_series_api_v1_experiments__run_id__observer_dose_series_get: {
        parameters: {
            query?: {
                resolution?: string;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObserverDoseComparisonResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_experiment_resources_api_v1_experiments__run_id__resources_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentResourcesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_experiment_resource_api_v1_experiments__run_id__resources__resource_name__get: {
        parameters: {
            query?: never;
            header?: {
                Range?: string | null;
            };
            path: {
                run_id: string;
                resource_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_snapshot_analysis_api_v1_experiments__run_id__snapshots__snapshot_id__analysis_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                snapshot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotAnalysisResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_snapshot_series_api_v1_experiments__run_id__snapshots__snapshot_id__series__series__get: {
        parameters: {
            query?: {
                rolling_window?: number;
                time_mode?: string;
            };
            header?: never;
            path: {
                run_id: string;
                snapshot_id: string;
                series: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotGraphSeriesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_live_api_v1_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveResponse"];
                };
            };
        };
    };
    get_live_events_api_v1_live_events_get: {
        parameters: {
            query?: never;
            header?: {
                "Last-Event-ID"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_log_archives_api_v1_logs_archives_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogArchivesResponse"];
                };
            };
        };
    };
    get_log_context_api_v1_logs_context_get: {
        parameters: {
            query?: {
                event_id?: string | null;
                created_at?: number | null;
                ended_at?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogContextResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_log_entries_api_v1_logs_entries_get: {
        parameters: {
            query?: {
                archive?: string;
                direction?: "head" | "tail" | "before" | "after";
                anchor_line?: number | null;
                page_size?: number;
                origin_uuid?: string | null;
                l_type?: string | null;
                level?: string | null;
                min_level?: string | null;
                exclude_type?: string[] | null;
                include_records?: boolean;
                line_from?: number | null;
                line_to?: number | null;
                since?: number | null;
                until?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogPageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_log_events_api_v1_logs_events_get: {
        parameters: {
            query?: {
                archive?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogEventsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_subsystems_api_v1_subsystems_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubsystemsResponse"];
                };
            };
        };
    };
    health_live_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    health_ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
